server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/wanx
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
feign:
  hystrix:
    enabled: true
#hystrix 熔断机制
hystrix:
  share-security-context: true
  commad:
    default:
      circuit-breaker:
        sleep=window-in-millisecondes: 100000
        force-closed: true
      execution:
        isolation:
          thread:
            timeout-in-milloseconds: 600000
ribbon.readTimeout: 120000            #设置请求处理的超时时间
ribbon.ConnectTimeout: 30000        #设置请求链接的超时时间
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl